### ISSUE TITLE
Display error message when collection field references model that doesn't exist

### ISSUE THREAD

**Issue by dstreet** [ExclamationLabs/sevr#1]

**Comment by dstreet** [comment]
Would be great if we could validate all collection definitions at startup using the following rules:

- Fields that have refs should only reference existing models
- `singular` and `fields` are required properties
- `singular` must be a String
- `fields
- `label` and `schemaType` are required field properties

**Comment by bpowers1215** [comment]
I have added validation at startup to check the above required properties/fields.

Still need to add validation for collection field model references
