### ISSUE TITLE
Can't update user without entering role

### ISSUE THREAD

**Issue by bpowers1215** [ExclamationLabs/sevr#10]
When updating an existing user, unable to save changes unless entering a valid `role` (even when attempting to leave role as is)

**Comment by dstreet** [comment]
Is this when trying to update via the CLI? If so, this may be an issue with the CLI not properly handling the enum data type.

**Comment by bpowers1215** [comment]
Thanks for the confirmation.  This is what I am being lead to believe in my search now as well.  I'll move this over to sevr-cli.  It seems the validation isn't displaying anymore either.
